from datetime import date, datetime, timezone

from fastapi import APIRouter, Depends
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.db.session import get_db
from app.dependencies.auth import get_current_user
from app.models.goal import Goal
from app.models.task import Task
from app.models.user import User
from app.schemas.dashboard import DashboardSummary, MetricItem, SectionItem

router = APIRouter()


def _normalise_status(status: str | None) -> str:
    return (status or "").strip().lower().replace("-", "_").replace(" ", "_")


def _is_active_goal_status(status: str | None) -> bool:
    return _normalise_status(status) in {"active", "in_progress"}


@router.get("/summary", response_model=DashboardSummary)
def get_dashboard_summary(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> DashboardSummary:
    goals = db.execute(
        select(Goal).where(Goal.user_id == current_user.id)
    ).scalars().all()

    tasks = db.execute(
        select(Task).where(Task.user_id == current_user.id)
    ).scalars().all()

    today = date.today().isoformat()

    active_goals    = sum(1 for g in goals if _is_active_goal_status(g.status))
    total_tasks     = len(tasks)
    completed_tasks = sum(1 for t in tasks if t.status == "done")
    open_tasks      = total_tasks - completed_tasks
    overdue_tasks   = sum(
        1 for t in tasks
        if t.due_date and t.status != "done" and t.due_date < today
    )
    task_rate = round((completed_tasks / total_tasks) * 100) if total_tasks > 0 else 0

    metrics = [
        MetricItem(
            value=str(active_goals),
            label="Active Goals",
            icon="target",
        ),
        MetricItem(
            value=str(completed_tasks),
            label="Tasks Done",
            icon="checkmark.circle.fill",
        ),
        MetricItem(
            value=f"{task_rate}%",
            label="Completion Rate",
            icon="chart.bar.fill",
        ),
        MetricItem(
            value=str(open_tasks),
            label="Open Tasks",
            icon="circle",
        ),
    ]

    # Contextual focus section — adapts to the user's actual data state.
    if total_tasks == 0 and len(goals) == 0:
        focus_content = (
            "Welcome to HELIOS. Start by adding a goal, then break it down into tasks. "
            "The AI Planner can help you map your first execution sprint."
        )
    elif overdue_tasks > 0:
        focus_content = (
            f"You have {overdue_tasks} overdue task{'s' if overdue_tasks > 1 else ''}. "
            "Review your Tasks tab and update priorities before adding new work."
        )
    elif open_tasks > 0:
        focus_content = (
            f"{open_tasks} open task{'s' if open_tasks > 1 else ''} across "
            f"{active_goals} active goal{'s' if active_goals != 1 else ''}. "
            "Use the AI Assistant to prioritize or the Planner to map your next sprint."
        )
    else:
        focus_content = (
            "Your task queue is clear. Review your active goals and plan your next sprint "
            "with the AI Planner."
        )

    sections = [
        SectionItem(
            title="AI Insight",
            icon="brain",
            content=(
                "Your daily briefing is generated by HELIOS AI from your current goals and tasks. "
                "Pull the briefing card below to see your personalized summary, priorities, and risks."
            ),
        ),
        SectionItem(
            title="Today's Focus",
            icon="flag.fill",
            content=focus_content,
        ),
    ]

    return DashboardSummary(
        metrics=metrics,
        sections=sections,
        system_status="online",
        last_updated=datetime.now(timezone.utc).isoformat(),
    )
